_target_: pbtrack.wrappers.TopDownMMPose
config_name: topdown_heatmap_hrformer_base_coco_384x288 # AP : 0.774
#config_name: topdown_heatmap_hrformer_small_coco_256x192 # AP : 0.738
#config_name: topdown_heatmap_hrformer_small_coco_384x288 # AP : 0.757
#config_name: topdown_heatmap_hrformer_base_coco_256x192 # AP : 0.753
path_to_checkpoint: ${project_dir}/weights/${.config_name}.pth
vis_kp_threshold: 0.4
min_num_vis_kp: 3