_target_: pbtrack.wrappers.TopDownMMPose
config_name: topdown_heatmap_hrnet_w32_posetrack18_256x192 # total : 83.0
#config_name: topdown_heatmap_hrnet_w32_posetrack18_384x288 # total : 83.6
#config_name: topdown_heatmap_hrnet_w48_posetrack18_256x192 # total : 84.4
#config_name: topdown_heatmap_hrnet_w48_posetrack18_384x288 # total : 84.5
path_to_checkpoint: ${project_dir}/weights/${.config_name}.pth