_target_: pbtrack.wrappers.MMPose

cfg:
  instance_min_confidence: 0.1  # threshold for np.mean(keypoint_confidences)
  keypoint_min_confidence: 0.1  # threshold for keypoint_confidence

  path_to_config: ${project_dir}/plugins/detect/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_w48_mpii_256x256.py
  path_to_checkpoint: ${project_dir}/weights/mmpose/hrnet_w48_mpii_256x256-92cab7bd_20200812.pth
  download_url: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_mpii_256x256-92cab7bd_20200812.pth

# configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_w32_mpii_256x256.py
# https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_mpii_256x256-6c4f923f_20200812.pth
# Mean: 0.9

# configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_w48_mpii_256x256.py
# https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_mpii_256x256-92cab7bd_20200812.pth
# Mean: 0.901
