_target_: pbtrack.wrappers.TopDownMMPose
#config_name: topdown_heatmap_hrnet_w32_coco_256x192_dark # AP: 0.757
#config_name: topdown_heatmap_hrnet_w32_coco_384x288_dark # AP: 0.766
#config_name: topdown_heatmap_hrnet_w48_coco_256x192_dark # AP: 0.764
config_name: topdown_heatmap_hrnet_w48_coco_384x288_dark # AP: 0.772
path_to_checkpoint: ${project_dir}/weights/${.config_name}.pth
