_target_: pbtrack.wrappers.MMPose

cfg:
  instance_min_confidence: 0.1  # threshold for np.mean(keypoint_confidences)
  keypoint_min_confidence: 0.1  # threshold for keypoint_confidence

  path_to_config: ${project_dir}/plugins/detect/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/litehrnet_30_mpii_256x256.py
  path_to_checkpoint: ${project_dir}/weights/mmpose/litehrnet30_mpii_256x256-faae8bd8_20210622.pth
  download_url: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_mpii_256x256-faae8bd8_20210622.pth

# configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/litehrnet_18_mpii_256x256.py
# https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet18_mpii_256x256-cabd7984_20210623.pth
# Mean: 0.859

# configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/litehrnet_30_mpii_256x256.py
# https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_mpii_256x256-faae8bd8_20210622.pth
# Mean: 0.869
