_target_: pbtrack.wrappers.TopDownMMPose

cfg:
  min_keypoints_score: 0.0  # keep only detections with a score higher
  min_keypoints_confidence: 0.0  # consider only keypoints with a confidence higher

  path_to_config: ${project_dir}/plugins/detect/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/res50_posetrack18_256x192.py
  path_to_checkpoint: ${project_dir}/weights/mmpose/res50_posetrack18_256x192-a62807c7_20201028.pth
  download_url: https://download.openmmlab.com/mmpose/top_down/resnet/res50_posetrack18_256x192-a62807c7_20201028.pth

# configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/res50_posetrack18_256x192.py
# https://download.openmmlab.com/mmpose/top_down/resnet/res50_posetrack18_256x192-a62807c7_20201028.pth
# Total: 81.0

# configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/res50_posetrack18_256x192.py
# https://download.openmmlab.com/mmpose/top_down/resnet/res50_posetrack18_256x192-a62807c7_20201028.pth
# Total: 75.2
