[tool.poetry]
name = "track-bench"
version = "1.0.0"
description = ""
authors = ["Vladimir Somers <vladimir.somers@uclouvain.be>", "Victor Joos <victor.joos@uclouvain.be>", "Baptiste Standaert <baptiste.standaert@uclouvain.be>"]
readme = "README.md"
packages = [{include = "pbtrack"}]

[tool.poetry.dependencies]
python = "^3.10"
# openpifpaf = {git="https://github.com/PbTrack/openpifpaf", branch="pbtrack", develop=true, extras=["dev","train","test"]}
poseval = {git="https://github.com/PbTrack/poseval", branch="pbtrack", develop=true}
posetrack21 = {path = "plugins/eval/PoseTrack21/posetrack21", develop = true}
posetrack21_mot = {path = "plugins/eval/PoseTrack21/posetrack21_mot", develop = true}
hydra-core = "^1.3"
lightning = "^2.0"
pytorch_lightning = "^2.0"
numpy = "^1.23.5"
openmim = "^0.3.9"
ultralytics = "8.0.61"
sphinx = "^7.2"
sphinx_rtd_theme = "^2.0"
myst-parser = "^2.0"
filterpy = "^1.4.5"
torch = {version = "1.13.1", source = "pytorch"}
torchvision = {version = "0.14.1", source = "pytorch"}
mmdet = "^3.2.0"
chumpy = "0.66"
mmpose = {git = "https://github.com/PbTrack/mmpose", rev = "pbtrack", develop = true}
lap = {git = "https://github.com/PbTrack/lap"}
track-bench-track = {path = "plugins/track", develop = true}
mmengine = "^0.10.1"
timm = "^0.9.12"
torchreid = {git = "https://github.com/victorjoos/bpbreid.git"}
openpifpaf = "^0.13.11"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu117"
priority = "explicit"


[[tool.poetry.source]]
name = "openmmlab"
url = "https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0"
priority = "explicit"

[tool.poetry.scripts]
trackbench = 'pbtrack.main:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
