# If save_file is not null, will save the tracking state
save_file: "/globalscratch/users/a/b/abolfazl/PbTrack_files/states/${experiment_name}.pklz"
compression: 0  # No compression, use 8 for compression

# the pipeline starts after the mentioned step with the state of the mentioned file
# [null, detect_multi, detect_single, reid]
load_step: null
load_file: null
