_target_: tracklab.wrappers.TrackEvalEvaluator


eval_set: ${dataset.eval_set}
trackeval_dataset_class: ${..dataset.trackeval_dataset_class}  # TrackEval dataset class to use for evaluation, e.g. "MotChallenge2DBox", as defined in the library package "trackeval.datasets". To be defined in the corresponding dataset config.
show_progressbar: True  # Show progressbar during evaluation
dataset_path: "${dataset.dataset_path}"

cfg:
  save_gt: False
  bbox_column_for_eval: "bbox_ltwh"  # which bbox column to use for evaluation: {"bbox_ltwh", "track_bbox_kf_ltwh", ...}
  metrics:  # List of performance metrics to compute as listed in "trackeval.metrics"
    - "HOTA"
    - "CLEAR"
    - "Identity"
  eval:  # mapped to trackeval/eval.py
    USE_PARALLEL: False  # TODO try
    NUM_PARALLEL_CORES: ${num_cores}
    BREAK_ON_ERROR: True  # Raises exception and exits with error
    PRINT_RESULTS: True
    PRINT_ONLY_COMBINED: True
    PRINT_CONFIG: False
    TIME_PROGRESS: False
    DISPLAY_LESS_PROGRESS: False
    OUTPUT_SUMMARY: True
    OUTPUT_EMPTY_CLASSES: True  # If False, summary files are not output for classes with no detections
    OUTPUT_DETAILED: True
    PLOT_CURVES: True
  dataset:  # mapped to trackeval/datasets/mot_challenge_2d_box.py
    GT_FOLDER: "eval/gt" # Location of GT data
    GT_LOC_FORMAT: '{gt_folder}/{seq}.txt' # '{gt_folder}/{seq}/gt/gt.txt'
    TRACKERS_FOLDER: 'eval/pred' # Trackers location
    TRACKER_SUB_FOLDER: '' # Tracker files are in TRACKER_FOLDER/tracker_name/TRACKER_SUB_FOLDER
    OUTPUT_FOLDER: "eval/results" # Where to save eval results (if None, same as TRACKERS_FOLDER)
    OUTPUT_SUB_FOLDER: '' # Output files are saved in OUTPUT_FOLDER/tracker_name/OUTPUT_SUB_FOLDER
    SPLIT_TO_EVAL: ${dataset.eval_set}
    PRINT_CONFIG: False
    DO_PREPROC: False
    TRACKER_DISPLAY_NAMES: null
