defaults:
  - default

_target_: tracklab.wrappers.SoccerNetMOT

dataset_path: ${data_dir}/SoccerNetMOT
annotation_path: ${data_dir}/SoccerNetMOT
trackeval_dataset_class: SoccerNetGS  # SoccerNetGS MotChallenge2DBox
