defaults:
  - default

_target_: tracklab.wrappers.SoccerNetMOT

dataset_path: '/home/user01/Amir/Tracking/SoccerNet'
annotation_path: '/home/user01/Amir/Tracking/SoccerNet'
trackeval_dataset_class: MotChallenge2DBox  # SoccerNetGS MotChallenge2DBox
eval_set: "val"

#dataset_path: ${data_dir}/SoccerNetMOT
#annotation_path: ${data_dir}/SoccerNetMOT

