_target_: pbtrack.wrappers.PoseTrack21Evaluator

cfg:
  eval_pose_estimation: True
  eval_pose_tracking: True
  eval_reid_pose_tracking: False # Not working
  eval_mot: True

  SEQS: "${dataset.vids_dict.val}"
  
  posetrack_trackers_folder: "eval/posetrack"
  posetrack_gt_folder: ${dataset.dataset_path}/posetrack_data/val
  
  mot_trackers_folder: "eval/mot"
  mot_gt_folder: ${dataset.dataset_path}/posetrack_mot/mot/val
  
  use_parallel: True
  num_parallel_cores: 8

  mot:
    dataset_path: ${dataset.dataset_path}
    use_ignore_regions: False
    ignore_iou_thres: 0.1
    vis_threshold: 0.1
