_target_: pbtrack.engine.OfflineTrackingEngine

num_workers: ${num_cores}
callbacks:
  progress:
    _target_: pbtrack.callbacks.RichProgressbar
  ignored_regions:
    _target_: pbtrack.callbacks.IgnoredRegions
    max_intersection: 0.9
  vis: ${visualization}
