_target_: pbtrack.engine.OfflineTrackingEngine

num_workers: ${num_cores}
callbacks:
  progress:
    _target_: pbtrack.callbacks.Progressbar
  ignored_regions:
    _target_: pbtrack.callbacks.IgnoredRegions
    iou_threshold: 0.9
  vis: ${visualization}
