_target_: wrappers.detect.dekr_api.DEKR

cfg:
  OUTPUT_DIR: ""
  NAME: "regression"
  LOG_DIR: ""
  DATA_DIR: ""
  GPUS: [0]
  WORKERS: 4
  PRINT_FREQ: 20
  AUTO_RESUME: False
  PIN_MEMORY: True
  RANK: 0
  VERBOSE: True
  DIST_BACKEND: "nccl"
  MULTIPROCESSING_DISTRIBUTED: True

  # Cudnn related params
  CUDNN:
    BENCHMARK: True
    DETERMINISTIC: False
    ENABLED: True

  # common params for NETWORK
  MODEL:
    NAME: "hrnet_dekr"
    INIT_WEIGHTS: True
    PRETRAINED: ""
    NUM_JOINTS: 17
    SPEC: CN(new_allowed=True)

  LOSS:
    WITH_HEATMAPS_LOSS: True
    HEATMAPS_LOSS_FACTOR: 1.0
    WITH_OFFSETS_LOSS: True
    OFFSETS_LOSS_FACTOR: 1.0

  # DATASET related params
  DATASET:
    ROOT: ""
    DATASET: "coco_kpt"
    DATASET_TEST: ""
    NUM_JOINTS: 17
    MAX_NUM_PEOPLE: 30
    TRAIN: "train2017"
    TEST: "val2017"
    DATA_FORMAT: "jpg"
    # training data augmentation
    MAX_ROTATION: 30
    MIN_SCALE: 0.75
    MAX_SCALE: 1.25
    SCALE_TYPE: "short"
    MAX_TRANSLATE: 40
    INPUT_SIZE: 512
    OUTPUT_SIZE: 128
    FLIP: 0.5
    # heatmap generator
    SIGMA: 2.0
    CENTER_SIGMA: 4.0
    BG_WEIGHT: 0.1
    # offset generator
    OFFSET_RADIUS: 4

  # train
  TRAIN:
    LR_FACTOR: 0.1
    LR_STEP: [90, 110]
    LR: 0.001
    OPTIMIZER: "adam"
    MOMENTUM: 0.9
    WD: 0.0001
    NESTEROV: False
    GAMMA1: 0.99
    GAMMA2: 0.0
    BEGIN_EPOCH: 0
    END_EPOCH: 140
    RESUME: False
    CHECKPOINT: ""
    IMAGES_PER_GPU: 32
    SHUFFLE: True

  # testing
  TEST:
    # size of images for each device
    IMAGES_PER_GPU: 32
    FLIP_TEST: True
    SCALE_FACTOR: [1]
    MODEL_FILE: ""
    POOL_THRESHOLD1: 300
    POOL_THRESHOLD2: 200
    NMS_THRE: 0.15
    NMS_NUM_THRE: 10
    KEYPOINT_THRESHOLD: 0.01
    DECREASE: 1.0
    MATCH_HMP: False
    ADJUST_THRESHOLD: 0.05
    MAX_ABSORB_DISTANCE: 75
    GUASSIAN_KERNEL: 6
    LOG_PROGRESS: True

  RESCORE:
    VALID: True
    GET_DATA: False
    END_EPOCH: 20
    LR: 0.001
    HIDDEN_LAYER: 256
    BATCHSIZE: 1024
    MODEL_FILE: "model/rescore/final_rescore_coco_kpt.pth"
    DATA_FILE: "data/rescore_data/rescore_dataset_train_coco_kpt"
