_target_: pbtrack.wrappers.detect.openpifpaf_api.OpenPifPaf
cfg:
  checkpoint: shufflenetv2k16
  batch_size: 2 # TODO get from engine config
  train:
    dataset: posetrack2021-cocokpst
    loader-workers: 8
    batch-size: 32
    lr: 0.0003
    momentum: 0.95
    epochs: 50
    b-scale: 10.0
    lr-decay-epochs: 5
    weight-decay: 0.00001
    stride-apply: 2
    posetrack-upsample: 2
    cocokp-upsample: 2
    cocokp-orientation-invariant: 0.1
    cocokp-blur: 0.1
    posetrack2021-train-annotations: "YOURPATH/*.json"
    posetrack2021-val-annotations: "YOURPATH/*.json"
    posetrack2021-data-root: "YOURPATH"
    cocokp-train-annotations: "YOURPATH/*.json"
    cocokp-val-annotations: "YOURPATH/*.json"
    cocokp-train-image-dir: "YOURPATH"
    cocokp-val-image-dir: "YOURPATH"
