defaults:
  - dataset: default

_target_: wrappers.reid.bpbreid_api.BPBReId
job_id: "${oc.env:SLURM_JOBID,0}" # TODO
save_path: reid
cfg:
  project:
    name: "Reconnaissance"
    experiment_name: ""
    notes: ""
    tags: ["test"]
    logger:
      use_clearml: False
      use_neptune: False
      use_tensorboard: False
      use_wandb: False
  data:
    root: "${data_dir}/reid"
    type: "image"
    sources: ["PoseTrack21"]
    targets: ["PoseTrack21"]
    height: 256
    width: 32
    combineall: False
    transforms: ["rc", "re"]
    masks:
      preprocess: "cc6" # 'none', 'full', 'id', 'ids', 'bs_fu', 'bs_fu_bb', 'mu_sc', 'four', 'four_no', 'four_v', 'four_v_pif', 'five_v', 'six', 'six_no', 'eight'
      background_computation_strategy: "sum" # threshold, diff_from_max
      softmax_weight: 0
      mask_filtering_threshold: 0.5
    save_dir: ""
    masks_dir: "gaussian" # 'pifpaf' 'pifpaf_maskrcnn_filtering' 'isp_6_parts'
    workers: 0

  sampler:
    train_sampler: RandomIdentitySampler # sampler for source train loader
    train_sampler_t: RandomIdentitySampler # sampler for target train loader
    num_instances: 4 # number of instances per identity for RandomIdentitySampler

  model:
    name: "bpbreid"
    pretrained: True
    save_model_flag: True
    load_weights: ""
    bpbreid:
      pooling: "gwap" # ['gap', 'gmp', 'gwap', 'gwap2']
      normalization: "identity" # 'batch_norm_2d' 'identity'
      mask_filtering_training: False
      mask_filtering_testing: True
      training_binary_visibility_score: True
      testing_binary_visibility_score: True
      last_stride: 1
      learnable_attention_enabled: False
      dim_reduce: "after_pooling" # 'none', 'before_pooling', 'after_pooling', 'after_pooling_with_dropout'
      dim_reduce_output: 256
      backbone: "resnet50" # 'hrnet32' 'resnet50' 'fastreid_resnet' 'fastreid_resnet_ibn' 'fastreid_resnet_nl' 'fastreid_resnet_ibn_nl'
      test_embeddings: ["bn_foreg", "parts"] #  ['globl', 'foreg', 'conct', 'parts']
      test_use_target_segmentation: "none" # 'none' 'hard' 'soft'
      shared_parts_id_classifier: False
      hrnet_pretrained_path: "" # FIXME refactor model loading (use urls)

  test:
    evaluate: True # test only
    start_eval: 40
    batch_size: 1
    batch_size_pairwise_dist_matrix: 5000
    normalize_feature: True
    dist_metric: "euclidean" # ['euclidean', 'cosine']
    visrank: True
    visrank_per_body_part: False
    vis_embedding_projection: False
    vis_feature_maps: False
    visrank_topk: 10
    visrank_count: 4
    visrank_q_idx_list: []
    part_based:
      dist_combine_strat: mean
