_target_: pbtrack.visualization.vis_engine.VisEngine
save_dir: "${save_dir}"
vis_cfg:
  max_videos: -1
  max_frames: -1
  images:
    save: True
  video:
    save: True
    fps: 30
    height: 540
    width: 960
  detection:
    bbox:
      show: False
      color: [255, 0, 0]
      thickness: 2
      print_conf: True
    pose:
      show: True
      radius: 1
      color: [255, 0, 0]
      thickness: 1
      print_conf: False
    heatmaps:
      show: True
  tracking:
    show: True
    color: [255, 0, 0]
    print_conf: False
    thickness: 2
    print_id: True