_target_: pbtrack.visualization.visualization_engine.VisualisationEngine
cfg:
  save_images: False
  save_videos: True

  process_n_videos: -1                      # -1 to process all videos
  process_n_frames_by_video: -1             # -1 to process all the frames
  video_fps: 5

  prediction:
    draw_bbox: True
    draw_keypoints: True
    draw_skeleton: True
    print_id: True
    print_bbox_confidence: True
    # debug
    print_keypoints_confidence: False
    draw_bpbreid_heatmaps: False
    heatmaps_display_threshold: 0.05

  ground_truth:
    draw_bbox: False
    draw_keypoints: False
    draw_skeleton: False
    draw_ignore_region: True
    # debug
    print_id: False
    print_bbox_confidence: False
    print_keypoints_confidence: False

  bbox: 
    displayed: ['detect'] # TODO not working ['detect', 'track']
    thickness: 1
    color_prediction: null                  # None is color by ID or RGB array
    color_ground_truth: null                # None is color by ID or RGB array
    color_no_id: [0, 0, 0]                  # RGB array

  text:
    font: 2
    scale: 0.6
    thickness: 1
    color_prediction: null                  # None is color by ID or RGB array
    color_ground_truth: null                # None is color by ID or RGB array
    color_no_id: [0, 0, 0]                  # RGB array

  keypoint:
    radius: 4
    thickness: -1                           # -1 to fill
    color_prediction: null                  # None is color by ID or RGB array
    color_ground_truth: null                # None is color by ID or RGB array
    color_no_id: [0, 0, 0]                  # RGB array

  skeleton:
    thickness: 2
    color_prediction: null                  # None is color by ID or RGB array
    color_ground_truth: null                # None is color by ID or RGB array
    color_no_id: [0, 0, 0]                  # RGB array
