defaults:
  - _self_
  - dataset: posetrack21
  - eval: posetrack21
  - engine: offline
  - machine: local
  - state: no_save
  - visualization: save_videos
  - detect_multiple: yolox
  - detect_single: hrnet_posetrack18
  - reid: bpbreid
  - track: bpbreid_strong_sort
  - jn_detect: easyocr

experiment_name: "pbtrack"
data_dir: "/globalscratch/users/a/b/abolfazl/PbTrack_files/dataset/"
num_cores: 4

train_detect: False
train_reid: False
test_tracking: True
use_wandb: True

# configure Hydra to use the current working directory
# and set up the output directory according to experiment_name
project_dir: "${hydra:runtime.cwd}"
hydra:
  job:
    chdir: True
  run:
    dir: "/globalscratch/users/a/b/abolfazl/PbTrack_files/outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  sweep:
    dir: "multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
