defaults:
  - _self_
  - dataset: posetrack21
  - eval: posetrack21
  - engine: offline
  - machine: local
  - state: no_save
  - visualization: save_videos
  - modules/pose_bottomup: openpifpaf
  - modules/reid: bpbreid
  - modules/track: oc_sort

pipeline: [pose_bottomup, reid, track]
experiment_name: "???"
data_dir: "???"
num_cores: 4

train_detect: False
train_reid: False
test_tracking: True
use_wandb: False

# configure Hydra to use the current working directory
# and set up the output directory according to experiment_name
project_dir: "${hydra:runtime.cwd}"
hydra:
  job:
    chdir: True
  run:
    dir: "outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  sweep:
    dir: "multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
