defaults:
  - _self_
  - detection: dekr
  - track: track
  - reid: bpbreid
  - dataset: image_folder
input_folder: "???"
project: track
name: exp
show_poses: true
show_tracks: true
save_imgs: false
save_vid: true
data_dir: "???"
project_dir: "${hydra:runtime.cwd}"
job_id: "???"

hydra:
  job:
    chdir: true # TODO : do we want this ?
