defaults:
  - _self_
  - detect: openpifpaf
  - reid: bpbreid
  - track: strong_sort
  - engine: offline
  - state: dont_keep
  - visualization: visualization
  - dataset: posetrack21
  - eval: posetrack21
experiment_name: "???"
data_dir: "???"

train_detect: True
train_reid: False
test_tracking: True
wandb_enabled: True

# configure Hydra to use the current working directory
# and set up the output directory according to experiment_name
project_dir: "${hydra:runtime.cwd}"
hydra:
  job:
    chdir: True
  run:
    dir: "outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  sweep:
    dir: "multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
