defaults:
  - _self_
  - detection: dekr
  - track: track
  - reid: local_bpbreid_test
  - dataset: image_folder
input_folder: "${oc.env:HOME}/projects/pb-track/images"
project: track
name: exp
show_poses: true
show_tracks: true
save_imgs: false
save_vid: true
data_dir: "${oc.env:HOME}/projects/reconn.ai.ssance"
project_dir: "${oc.env:HOME}/projects/pb-track"
job_id: "???"

hydra:
  job:
    chdir: true # TODO : do we want this ?
