defaults:
  - _self_
  - dataset: posetrack21
  - detect: openpifpaf
  - engine: offline
  - reid: bpbreid
  - eval: posetrack21
  - state: dont_keep
  - track: strong_sort
  - visualization: visualization
experiment_name: "???"
data_dir: "???"

train_detect: false
train_reid: false
test_tracking: true

# configure Hydra to use the current working directory
# and set up the output directory according to experiment_name
project_dir: "${hydra:runtime.cwd}"
hydra:
  job:
    chdir: true
  run:
    dir: "outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  sweep:
    dir: "multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
