defaults:
  - _self_
  - detection: openpifpaf
  - track: track
  - reid: bpbreid
  - dataset: posetrack21
data_dir: "???"
project_dir: "${hydra:runtime.cwd}"
job_id: "???"

hydra:
  job:
    chdir: true # TODO : do we want this ?
