defaults:
  - _self_
  - detection: dekr
  - track: track
  - reid: bpbreid
  - visualization: vis
  - dataset: posetrack21
  - eval: posetrack21
data_dir: "???"
project_dir: "${hydra:runtime.cwd}"
job_id: "???"
save_dir: "???"

hydra:
  job:
    chdir: true # TODO : do we want this ?
