_target_: pbtrack.wrappers.MMDetection

cfg:
  min_bbox_score: 0.2  # threshold on bbox confidence

  path_to_config: ${project_dir}/plugins/detect/mmdetection/configs/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_1x_coco.py
  path_to_checkpoint: ${project_dir}/weights/mmdetection/cascade_rcnn_x101_64x4d_fpn_1x_coco_20200515_075702-43ce6a30.pth
  download_url: https://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_1x_coco/cascade_rcnn_x101_64x4d_fpn_1x_coco_20200515_075702-43ce6a30.pth

# configs/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_1x_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_1x_coco/cascade_rcnn_x101_64x4d_fpn_1x_coco_20200515_075702-43ce6a30.pth
# box AP: 44.7

# configs/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_20e_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_20e_coco/cascade_rcnn_x101_64x4d_fpn_20e_coco_20200509_224357-051557b1.pth
# box AP: 44.5

# configs/cascade_rcnn/cascade_rcnn_x101_32x4d_fpn_20e_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_x101_32x4d_fpn_20e_coco/cascade_rcnn_x101_32x4d_fpn_20e_coco_20200906_134608-9ae0a720.pth
# box AP: 43.7
