_target_: pbtrack.wrappers.MMPoseMultiple

cfg:
  instance_min_confidence: 0.1
  keypoint_min_confidence: 0.1

  bbox:
    top_extend_factor: 0.03
    bottom_extend_factor: 0.1
    left_right_extend_factor: 0.1

  path_to_config: ${project_dir}/plugins/detect/mmpose/configs/body/2d_kpt_sview_rgb_img/dekr/crowdpose/hrnet_w48_crowdpose_640x640_multiscale.py
  path_to_checkpoint: ${project_dir}/weights/mmpose/hrnet_w48_crowdpose_640x640-ef6b6040_20220930.pth
  download_url: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_crowdpose_640x640-ef6b6040_20220930.pth

# configs/body/2d_kpt_sview_rgb_img/dekr/crowdpose/hrnet_w32_crowdpose_512x512.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_crowdpose_512x512-685aff75_20220924.pth
# AP: 0.663

# configs/body/2d_kpt_sview_rgb_img/dekr/crowdpose/hrnet_w48_crowdpose_640x640.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_crowdpose_640x640-ef6b6040_20220930.pth
# AP: 0.682

# configs/body/2d_kpt_sview_rgb_img/dekr/crowdpose/hrnet_w32_crowdpose_512x512_multiscale.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_crowdpose_512x512-685aff75_20220924.pth
# AP: 0.692

# configs/body/2d_kpt_sview_rgb_img/dekr/crowdpose/hrnet_w48_crowdpose_640x640_multiscale.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_crowdpose_640x640-ef6b6040_20220930.pth
# AP: 0.696
