_target_: pbtrack.wrappers.BottomUpMMPose

cfg:
  instance_min_confidence: 0.2
  keypoint_min_confidence: 0.0

  bbox:
    top_extend_factor: 0.03
    bottom_extend_factor: 0.1
    left_right_extend_factor: 0.1

  path_to_config: ${project_dir}/plugins/detect/mmpose/configs/body/2d_kpt_sview_rgb_img/dekr/coco/hrnet_w48_coco_640x640_multiscale.py
  path_to_checkpoint: ${project_dir}/weights/mmpose/hrnet_w48_coco_640x640-8854b2f1_20220930.pth
  download_url: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_coco_640x640-8854b2f1_20220930.pth

# configs/body/2d_kpt_sview_rgb_img/dekr/coco/hrnet_w32_coco_512x512.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_coco_512x512-2a3056de_20220928.pth
# AP: 0.68

# configs/body/2d_kpt_sview_rgb_img/dekr/coco/hrnet_w48_coco_640x640.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_coco_640x640-8854b2f1_20220930.pth
# AP: 0.709

# configs/body/2d_kpt_sview_rgb_img/dekr/coco/hrnet_w32_coco_512x512_multiscale.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_coco_512x512-2a3056de_20220928.pth
# AP: 0.705

# configs/body/2d_kpt_sview_rgb_img/dekr/coco/hrnet_w48_coco_640x640_multiscale.py
# https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_coco_640x640-8854b2f1_20220930.pth
# AP: 0.722
