_target_: pbtrack.wrappers.MMDetection

cfg:
  min_bbox_score: 0.2  # threshold on bbox confidence

  path_to_config: ${project_dir}/plugins/detect/mmdetection/configs/faster_rcnn/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco.py
  path_to_checkpoint: ${project_dir}/weights/mmdetection/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco_20210524_124528-26c63de6.pth
  download_url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco_20210524_124528-26c63de6.pth

# configs/faster_rcnn/faster_rcnn_r50_fpn_tnr-pretrain_1x_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_tnr-pretrain_1x_coco/faster_rcnn_r50_fpn_tnr-pretrain_1x_coco_20220320_085147-efedfda4.pth
# box AP: 40.2

# configs/faster_rcnn/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco_20210524_124528-26c63de6.pth
# box AP: 43.1

# configs/faster_rcnn/faster_rcnn_x101_32x4d_fpn_mstrain_3x_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_32x4d_fpn_mstrain_3x_coco/faster_rcnn_x101_32x4d_fpn_mstrain_3x_coco_20210524_124151-16b9b260.pth
# box AP: 42.5