_target_: pbtrack.wrappers.MMDetection

cfg:
  min_bbox_score: 0.2  # threshold on bbox confidence

  path_to_config: ${project_dir}/plugins/detect/mmdetection/configs/yolox/yolox_x_8x8_300e_coco.py
  path_to_checkpoint: ${project_dir}/weights/mmdetection/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
  download_url: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth

# configs/yolox/yolox_s_8x8_300e_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_s_8x8_300e_coco/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth
# box AP: 40.5

# configs/yolox/yolox_l_8x8_300e_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_l_8x8_300e_coco/yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth
# box AP: 49.4

# configs/yolox/yolox_x_8x8_300e_coco.py
# https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
# box AP: 50.9
