_target_: pbtrack.wrappers.YOLOv8Pose

cfg:
  # models available :
  # yolov8n-pose.pt, yolov8s-pose.pt, yolov8m-pose.pt, yolov8l-pose.pt, yolov8x-pose.pt, yolov8x-pose-p6.pt
  # those models will be downloaded automatically if not found in the path
  path_to_checkpoint: yolov8x-pose-p6.pt

  min_confidence: 0.4
